use reelratings;
insert into movie values (1, 'The Shawshank Redemption', 'Epic');
insert into movie values (2, 'The Godfather', 'Epic');
insert into movie values (3, 'The Dark Knight', 'Action Epic');
insert into movie values (4, 'The Godfather Part II', 'Epic');
insert into movie values (5, '12 Angry Men', 'Legal Drama');
insert into movie values (6, 'The Lord of the Rings: The Return of the King', 'Adventure Epic');
insert into movie values (7, 'Schindlers List', 'Docudrama');
insert into movie values (8, 'Pulp Fiction', 'Dark Comedy');
insert into movie values (9, 'The Lord of the Rings: The Fellowship of the Ring', 'Adventure Epic');
insert into movie values (10, 'The Good, the Bad and the Ugly', 'Adventure Epic'); 
insert into movie values (11, 'Forrest Gump', 'Epic');
insert into movie values (12, 'The Lord of the Rings: The Two Towers', 'Adventure Epic');
insert into movie values (13, 'Fight Club', 'Psychological Drama');
insert into movie values (14, 'Inception', 'Action Epic');
insert into movie values (15, 'Star Wars: Episode V - The Empire Strikes Back', 'Action Epic'); 
insert into movie values (16, 'The Matrix', 'Action Epic');
insert into movie values (17, 'Goodfellas', 'Docudrama');
insert into movie values (18, 'One Flew Over the Cuckoos Nest', 'Medical Drama'); 
insert into movie values (19, 'Interstellar', 'Adventure Epic');
insert into movie values (20, 'Se7en', 'Cop Drama');
insert into movie values (21, 'Its a Wonderful Life', 'Romance');
insert into movie values (22, 'Seven Samurai', 'Action Epic');
insert into movie values (23, 'The Silence of the Lambs', 'Psychological Drama');
insert into movie values (24, 'Saving Private Ryan', 'War Epic');
insert into movie values (25, 'City of God', 'Coming-of-Age');
insert into movie values (26, 'The Green Mile', 'Period Drama');
insert into movie values (27, 'Life Is Beautiful', 'Period Drama');
insert into movie values (28, 'Terminator 2: Judgement Day', 'Action Epic'); 
insert into movie values (29, 'Star Wars: Episode IV - A New Hope', 'Action Epic');
insert into movie values (30, 'Back to the Future', 'Comedy');
insert into movie values (31, 'Spirited Away', 'Anime');
insert into movie values (32, 'The Pianist', 'Docudrama');
insert into movie values (33, 'Parasite', 'Dark Comedy');
insert into movie values (34, 'Gladiator', 'Action Epic');
insert into movie values (35, 'Psycho', 'Psychological Horror');
insert into movie values (36, 'The Lion King', 'Animal Adventure');
insert into movie values (37, 'The Departed', 'Cop Drama');
insert into movie values (38, 'Grave of the Fireflies', 'Anime');
insert into movie values (39, 'Spider-Man: Across the Spider-Verse', 'Superhero');
insert into movie values (40, 'Whiplash', 'Psychological Drama');
insert into movie values (41, 'American History X', 'Prison Drama');
insert into movie values (42, 'Léon: The Professional', 'Action');
insert into movie values (43, 'The Prestige', 'Period Drama');
insert into movie values (44, 'Harakiri', 'Period Drama');
insert into movie values (45, 'Casablanca', 'Drama');
insert into movie values (46, 'The Usual Suspects', 'Psychological Drama');
insert into movie values (47, 'The Intouchables', 'Docudrama');
insert into movie values (48, 'Cinema Paradiso', 'Coming-of-Age');
insert into movie values (49, 'Dune: Part Two', 'Action Epic');
insert into movie values (50, 'Modern Times', 'Comedy');
